CREATE DATABASE PEOPLES_PRIORITY_DB;
USE PEOPLES_PRIORITY_DB;

CREATE TABLE CITIZENS(
CITIZEN_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR(100) UNIQUE,
PASSWORD VARCHAR(255),
MOBILE_NUMBER VARCHAR(15),
PREFERRED_LANG VARCHAR(15)
);

CREATE TABLE ADMINS(
ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(100),
EMAIL VARCHAR(100) UNIQUE,
PASSWORD VARCHAR(255),
CONSTITUENCY VARCHAR(15)
);

CREATE TABLE SUGGESTIONS(
SUGGESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
CITIZEN_ID INT,
ADMIN_ID INT,
FOREIGN KEY(CITIZEN_ID) REFERENCES CITIZENS(CITIZEN_ID),
FOREIGN KEY(ADMIN_ID) REFERENCES ADMINS(ADMIN_ID),
CATEGORY VARCHAR(50),
TITLE VARCHAR(200),
DESCRIPTION TEXT,
IMAGE_PATH VARCHAR(255),
VOICE_PATH VARCHAR(255),
LOCATION VARCHAR(200),
LATITUDE DECIMAL(10,8),
LONGITUDE DECIMAL(11,8),
STATUS ENUM('PENDING','IN_REVIEW','RESOLVED'),
AI_PRIORITY_SCORE DECIMAL(5,2),
AI_CATEGORY VARCHAR(50),
DUPLICATE_CLUSTER VARCHAR(100),
CREATED_AT DATETIME,
LANGUAGE VARCHAR(30)
);

INSERT INTO CITIZENS VALUES(
101,"RAM GUPTE","RAM123@GMAIL.COM","RG#456","9822420113","MARATHI");

SELECT * FROM CITIZENS;

INSERT INTO CITIZENS VALUES(
102,"TANISHKA TAKAWALE","TANU189@GMAIL.COM","TAN#455","8080175849","ENGLISH");

ALTER TABLE CITIZENS 
ADD COLUMN STATE VARCHAR(100),
ADD COLUMN DISTRICT VARCHAR(100),
ADD COLUMN CONSTITUENCY VARCHAR(150);

ALTER TABLE CITIZENS 
ADD COLUMN confirm_password VARCHAR(100);

ALTER TABLE CITIZENS DROP COLUMN confirm_password;

INSERT INTO ADMINS VALUES(
1001,"SHIV THAKUR","SHIV892@GMAIL.COM","SHIV_892","VADGAON");

SELECT * FROM ADMINS;

DESC SUGGESTIONS;

SELECT * FROM SUGGESTIONS;

ALTER TABLE SUGGESTIONS ADD COLUMN AI_SUMMARY VARCHAR(300);

ALTER TABLE SUGGESTIONS
MODIFY COLUMN STATUS ENUM('Pending', 'In Progress', 'Resolved')
DEFAULT 'Pending';